/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Reservasi extends javax.swing.JFrame {

    /**
     * Creates new form Reservasi
     */
    public Reservasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfTujuan = new javax.swing.JTextField();
        jsDws = new javax.swing.JSpinner();
        jsInf = new javax.swing.JSpinner();
        btnPesan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfAsal1 = new javax.swing.JTextField();
        tfAsal2 = new javax.swing.JTextField();
        tfAsal3 = new javax.swing.JTextField();
        tfAsal4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("FORM PEMESANAN TIKET KERETA API");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 200, 40);

        jLabel2.setText("DEWASA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 310, 150, 30);

        jLabel3.setText("NO KTP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 170, 30);

        jLabel4.setText("STASIUN ASAL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 200, 150, 30);

        jLabel5.setText("STASIUN TUJUAN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 240, 150, 30);

        jLabel6.setText("INFANT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 280, 150, 30);

        tfTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTujuanActionPerformed(evt);
            }
        });
        getContentPane().add(tfTujuan);
        tfTujuan.setBounds(190, 240, 150, 30);
        getContentPane().add(jsDws);
        jsDws.setBounds(190, 310, 70, 30);
        getContentPane().add(jsInf);
        jsInf.setBounds(190, 280, 70, 30);

        btnPesan.setText("Pesan Sekarang");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesan);
        btnPesan.setBounds(140, 370, 120, 30);

        jLabel7.setText("TANGGAL KEBERANGKATAN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 160, 170, 30);

        jLabel8.setText("NAMA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 80, 170, 30);

        tfAsal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAsal1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfAsal1);
        tfAsal1.setBounds(190, 200, 150, 30);

        tfAsal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAsal2ActionPerformed(evt);
            }
        });
        getContentPane().add(tfAsal2);
        tfAsal2.setBounds(190, 80, 150, 30);

        tfAsal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAsal3ActionPerformed(evt);
            }
        });
        getContentPane().add(tfAsal3);
        tfAsal3.setBounds(190, 160, 150, 30);

        tfAsal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAsal4ActionPerformed(evt);
            }
        });
        getContentPane().add(tfAsal4);
        tfAsal4.setBounds(190, 120, 150, 30);

        setBounds(0, 0, 453, 456);
    }// </editor-fold>//GEN-END:initComponents

    private void tfTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTujuanActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        Result x = new Result();
        x.setVisible(true);
      
    }//GEN-LAST:event_btnPesanActionPerformed

    private void tfAsal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAsal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAsal1ActionPerformed

    private void tfAsal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAsal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAsal2ActionPerformed

    private void tfAsal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAsal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAsal3ActionPerformed

    private void tfAsal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAsal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAsal4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jsDws;
    private javax.swing.JSpinner jsInf;
    private javax.swing.JTextField tfAsal1;
    private javax.swing.JTextField tfAsal2;
    private javax.swing.JTextField tfAsal3;
    private javax.swing.JTextField tfAsal4;
    private javax.swing.JTextField tfTujuan;
    // End of variables declaration//GEN-END:variables
}
